import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import fs from "fs";
import path from 'path'
import yaml from "js-yaml";

interface IndexData {
  heading: string;
  subheading: string;
  background_image: string;
}

type IndexProps = {
  data: IndexData;
};
const Home: NextPage<IndexProps> = ({ data }) => {
  console.log('data is ', data)
  const { heading, subheading, background_image } = data;
  console.log(heading, subheading, background_image)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="h-[500px] flex items-center justify-center" style={{ backgroundImage: `url(${background_image})` }}>
          <div className="max-w-3xl flex flex-col justify-center gap-4">
            <h1 className="text-4xl uppercase">{heading}</h1>
            <p>{subheading}</p>
            <button className="border self-start px-4 py-3 cursor-pointer bg-blue-700 text-white rounded-md mt-3">
              Learn More
            </button>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const indexFilePath = path.join(process.cwd(), "public", "data", "index.yml")
  const indexData = fs.readFileSync(indexFilePath, "utf-8");
  const indexConfig = yaml.load(indexData) as IndexData;

 return {
   props: {
     data: indexConfig,
   },
 };
};
